package academy.wakanda.sorrileadsbe.domain;

public enum MultipleChoice {
    APARELHO_FIXO_OU_INVISÍVEL, IMPLANTES_E_PRÓTESES, LIMPEZA_E_REVISAO_GERAL,
    CLAREAMENTO_DENTAL, BOTOX, FACETAS_DE_RESINA_OU_PORCELANA, OUTROS_PROBLEMAS;

}
